import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const AUTHENTIC_SNEAKERS = [
  // =========================================================================
  // NIKE (24 Distinct Models)
  // =========================================================================
  {
    name: "Nike Air Force 1 '07 Triple White",
    description: "The radiance lives on in the Nike Air Force 1 '07, the b-ball icon that puts a fresh spin on crisp leather, bold details and the perfect amount of flash.",
    price: 115.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Nike",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11", "UK 12"]),
    stock: 50,
  },
  {
    name: "Nike Dunk Low Retro Panda",
    description: "Created for the hardwood but taken to the streets, the 80s b-ball icon returns with perfectly shined overlays and classic black-and-white color blocking.",
    price: 125.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Nike",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 42,
  },
  {
    name: "Nike Air Max 90 Infrared OG",
    description: "Nothing as fly, nothing as comfortable, nothing as proven. The Nike Air Max 90 stays true to its OG running roots with the iconic Waffle sole and visible Max Air cushioning.",
    price: 130.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1575537302964-96cd47c06b1b?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Nike",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 30,
  },
  {
    name: "Nike Air Max 97 Silver Bullet",
    description: "Featuring the original ripple design inspired by Japanese bullet trains, the Air Max 97 lets you push your style full speed ahead with full-length Max Air unit.",
    price: 185.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Nike",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 22,
  },
  {
    name: "Nike Blazer Mid '77 Vintage White/Black",
    description: "Styled for the 70s. Loved in the 80s. Classic in the 90s. Ready for the future. The Nike Blazer Mid '77 Vintage delivers a timeless design with retro suede accents.",
    price: 105.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1560343090-f0409e92791a?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Nike",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 40,
  },
  {
    name: "Nike Air Max Plus TN Sunset Orange",
    description: "Featuring tuned Air technology and flame-like TPU cage overlays, this 1998 icon makes a defiant streetwear statement in gradient sunset orange.",
    price: 190.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Nike",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 25,
  },
  {
    name: "Nike ZoomX Vaporfly Next% 3 Elite",
    description: "Engineered for race day dominance. Built with ultra-responsive ZoomX foam and a full-length carbon fiber flyplate for maximum propulsion.",
    price: 220.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?q=80&w=1000&auto=format&fit=crop"]),
    category: "sports",
    brand: "Nike",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 18,
  },
  {
    name: "Nike Air Zoom Pegasus 40",
    description: "A springy ride for every run, the Pegasus returns with neutral support, highly tuned single-layer mesh, and responsive dual Zoom Air units.",
    price: 140.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1586525198428-225f6f12cff5?q=80&w=1000&auto=format&fit=crop"]),
    category: "sports",
    brand: "Nike",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 55,
  },
  {
    name: "Nike Tech Hera Chunky Platform",
    description: "Inspired by early 2000s running, the Tech Hera features a chunky lifted midsole and subtly layered textile upper for bold chunky streetwear fits.",
    price: 110.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1618677831708-0e7fda3148b4?q=80&w=1000&auto=format&fit=crop"]),
    category: "chunky",
    brand: "Nike",
    sizes: JSON.stringify(["UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"]),
    stock: 28,
  },
  {
    name: "Nike V2K Run Metallic Platinum",
    description: "Forward, rewind. The V2K remasters early 2000s Vomero runners with metallic chrome cage hits, chunky heel bevels, and dual-density foam cushioning.",
    price: 120.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=1000&auto=format&fit=crop"]),
    category: "chunky",
    brand: "Nike",
    sizes: JSON.stringify(["UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"]),
    stock: 34,
  },
  {
    name: "Nike Dunk Low 'Goku Super Saiyan' Edition",
    description: "Special anime collector drop showcasing golden aura yellow swoosh accents over orange and royal blue varsity leather overlays.",
    price: 160.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1617606002806-94e279c22567?q=80&w=1000&auto=format&fit=crop"]),
    category: "anime",
    brand: "Nike",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 15,
  },
  {
    name: "Nike Air Force 1 'Jujutsu Kaisen Gojo' Limited",
    description: "Domain Expansion tribute featuring icy translucent soles, sleek obsidian leather, and blindfold-textured purple lace dubraes.",
    price: 175.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1580906853203-f493cee9ff28?q=80&w=1000&auto=format&fit=crop"]),
    category: "anime",
    brand: "Nike",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 12,
  },
  {
    name: "Nike Dunk Low 'One Piece Gear 5' Edition",
    description: "Manga collector drop featuring sun-god white cracked leather, cloud-purple swoosh detailing, and drum-of-liberation insoles.",
    price: 180.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=1000&auto=format&fit=crop"]),
    category: "anime",
    brand: "Nike",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 10,
  },
  {
    name: "Nike Cortez Vintage 72 Leather",
    description: "Bill Bowerman's 1972 track masterpiece built for comfortable daily beating with signature herringbone outsole and vibrant red swoosh.",
    price: 90.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1512374382149-233c42b661ac?q=80&w=1000&auto=format&fit=crop"]),
    category: "women",
    brand: "Nike",
    sizes: JSON.stringify(["UK 4", "UK 5", "UK 6", "UK 7", "UK 8"]),
    stock: 45,
  },
  {
    name: "Nike Air Max 1 '86 OG Big Bubble",
    description: "The holy grail of sneaker design that started the visible Air revolution in vibrant varsity red and light neutral grey suede panels.",
    price: 150.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Nike",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 24,
  },
  {
    name: "Nike React Infinity Run Flyknit 3",
    description: "Flyknit breathability engineered with rocker-geometry React foam midsole for smooth transition and maximum knee stability.",
    price: 160.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1565814636199-ae8133055c1c?q=80&w=1000&auto=format&fit=crop"]),
    category: "sports",
    brand: "Nike",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"]),
    stock: 35,
  },
  {
    name: "Nike Air Max 270 Black Neon",
    description: "Boasting Nike's biggest heel Air unit yet, delivering a super-soft ride that feels as impossible as it looks with breathable engineered mesh.",
    price: 160.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1000&auto=format&fit=crop"]),
    category: "women",
    brand: "Nike",
    sizes: JSON.stringify(["UK 4", "UK 5", "UK 6", "UK 7", "UK 8"]),
    stock: 26,
  },
  {
    name: "Nike Dunk High Retro University Blue",
    description: "High-top court legend with premium ankle padding, rich two-tone Carolina blue leather panels, and collegiate heritage.",
    price: 135.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1608667508764-33cf0726b13a?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Nike",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 30,
  },
  {
    name: "Nike Air Presto Triple Black",
    description: "The original T-shirt for your feet featuring stretchy sock-like mesh upper with molded midfoot cage support and Air cushioning.",
    price: 140.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1539185441755-769473a23570?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Nike",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 32,
  },
  {
    name: "Nike Zoom Invincible 3 Max Cushion",
    description: "Maximum ZoomX foam cushioning engineered to protect joints during daily high-mileage runs and long recovery strolls.",
    price: 190.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?q=80&w=1000&auto=format&fit=crop"]),
    category: "sports",
    brand: "Nike",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 20,
  },
  {
    name: "Nike Flex Runner 2 Kids Slip-On",
    description: "Slip-on design with stretchy breathable fabric, leather reinforcement, and flexible grooves made for active playtime.",
    price: 55.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1514989940723-e8e51635b782?q=80&w=1000&auto=format&fit=crop"]),
    category: "kids",
    brand: "Nike",
    sizes: JSON.stringify(["UK 1", "UK 2", "UK 3", "UK 4", "UK 5"]),
    stock: 60,
  },
  {
    name: "Nike Calm Mule Sandal Oatmeal",
    description: "Seamless minimalist water-resistant foam mule with contoured footbed and full-length rubber grip for relaxed recovery.",
    price: 65.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=1000&auto=format&fit=crop"]),
    category: "women",
    brand: "Nike",
    sizes: JSON.stringify(["UK 4", "UK 5", "UK 6", "UK 7", "UK 8"]),
    stock: 38,
  },
  {
    name: "Nike SB Dunk Low Pro Laser Orange",
    description: "Padded tongue, Zoom Air heel unit, and durable suede construction purpose-built for skateboarding and street culture.",
    price: 120.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1603808033192-082d6919d3e1?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Nike",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 20,
  },
  {
    name: "Nike Court Vision Low Triple White",
    description: "Fastbreak 80s basketball style meets the fast-paced culture of today's game with crisp faux-leather upper and stitched cupsole.",
    price: 75.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1562183241-b937e95585b6?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Nike",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 45,
  },

  // =========================================================================
  // JORDAN (16 Distinct Models)
  // =========================================================================
  {
    name: "Air Jordan 1 Retro High OG 'Chicago Lost & Found'",
    description: "Recreating the magic of the 1985 original with aged vintage collar cracking, muslin tongue, and classic Varsity Red leather.",
    price: 210.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Jordan",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11", "UK 12"]),
    stock: 18,
  },
  {
    name: "Air Jordan 4 Retro 'Military Black'",
    description: "One of the cleanest Jordan 4 colorways ever made, featuring smooth white leather, neutral grey suede toe cap, and deep black wing eyelets.",
    price: 220.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Jordan",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 14,
  },
  {
    name: "Air Jordan 3 Retro 'White Cement Reimagined'",
    description: "Tinker Hatfield's iconic masterpiece with signature elephant print mudguards, Nike Air heel branding, and vintage midsole wash.",
    price: 215.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1579446650033-706d3cb8f219?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Jordan",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 16,
  },
  {
    name: "Air Jordan 1 Mid 'Bred Toe'",
    description: "Rock the iconic Black and Gym Red colorway in an everyday Mid silhouette crafted from genuine leather and encapsulated Air-Sole cushioning.",
    price: 135.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1612902377756-414b2139d5e2?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Jordan",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 35,
  },
  {
    name: "Air Jordan 1 Low 'Shadow Toe'",
    description: "Low-cut versatile street staple featuring medium grey, black and white panels with Wings logo embroidered on the heel.",
    price: 120.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Jordan",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 40,
  },
  {
    name: "Air Jordan 4 Retro 'Thunder Yellow'",
    description: "Electrifying tour yellow hits on the underlays and midsole contrasted against midnight black nubuck leather.",
    price: 215.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1617606002806-94e279c22567?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Jordan",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 15,
  },
  {
    name: "Air Jordan 1 High 'Naruto Shippuden Sage' Edition",
    description: "Anime collaboration featuring vibrant toad-sage orange scroll accents, black collar clouds, and Uzumaki crest heel stamps.",
    price: 195.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1590673846749-e25880d778a6?q=80&w=1000&auto=format&fit=crop"]),
    category: "anime",
    brand: "Jordan",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 12,
  },
  {
    name: "Air Jordan 4 Retro 'Akira Neo-Tokyo Cyber'",
    description: "Cyberpunk capsule drop in capsule pill crimson and futuristic neon yellow accents with distressed industrial mesh.",
    price: 210.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=1000&auto=format&fit=crop"]),
    category: "anime",
    brand: "Jordan",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 8,
  },
  {
    name: "Air Jordan 11 Retro 'Concord White'",
    description: "The crown jewel of Tinker Hatfield's designs featuring gleaming black patent leather, white ballistic mesh, and icy blue translucent outsoles.",
    price: 225.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Jordan",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 10,
  },
  {
    name: "Jordan Stadium 90 Chunky Street",
    description: "Comfort-first chunky silhouette blending elements from the AJ1 and AJ5 with Formula 23 foam midsole cushioning.",
    price: 140.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1588117305388-c2631a279f82?q=80&w=1000&auto=format&fit=crop"]),
    category: "chunky",
    brand: "Jordan",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 30,
  },
  {
    name: "Jordan Nu Retro 1 Low Obsidian",
    description: "Early 2000s low-top revival with oversized debossed Wings logo across the side panels and split-toe construction.",
    price: 110.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1581655353564-df123a1eb820?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Jordan",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"]),
    stock: 25,
  },
  {
    name: "Air Jordan 5 Retro 'University Blue UNC'",
    description: "Paying homage to MJ's alma mater with premium Carolina blue nubuck, reflective 3M silver tongue, and fighter jet shark teeth.",
    price: 225.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Jordan",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 14,
  },
  {
    name: "Jordan Spizike Low Bred Cement",
    description: "Iconic Spike Lee hybrid mashup taking the best elements of the AJ3, AJ4, AJ5, and AJ6 into a fierce low-top package.",
    price: 165.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Jordan",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"]),
    stock: 22,
  },
  {
    name: "Jordan 1 Retro High OG Kids Chicago",
    description: "Miniaturized legend for the next generation of hoopers with durable genuine leather and soft flexible cupsole.",
    price: 85.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1514989940723-e8e51635b782?q=80&w=1000&auto=format&fit=crop"]),
    category: "kids",
    brand: "Jordan",
    sizes: JSON.stringify(["UK 1", "UK 2", "UK 3", "UK 4", "UK 5"]),
    stock: 45,
  },
  {
    name: "Air Jordan 1 Mid SE 'Craft Coconut Milk'",
    description: "Deconstructed lifestyle interpretation with inside-out layered canvas, raw foam collar trims, and creamy earth tones.",
    price: 145.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=1000&auto=format&fit=crop"]),
    category: "women",
    brand: "Jordan",
    sizes: JSON.stringify(["UK 4", "UK 5", "UK 6", "UK 7", "UK 8"]),
    stock: 28,
  },
  {
    name: "Jordan Max Aura 5 Triple Black",
    description: "Stealth basketball sneaker equipped with visible Air heel pod, sturdy leather containment, and aggressive multi-surface herringbone tread.",
    price: 130.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1539185441755-769473a23570?q=80&w=1000&auto=format&fit=crop"]),
    category: "sports",
    brand: "Jordan",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 32,
  },

  // =========================================================================
  // ADIDAS (20 Distinct Models)
  // =========================================================================
  {
    name: "Adidas Samba OG Core Black/White Gum",
    description: "From football pitches to street fashion royalty. The Samba OG pairs soft leather with iconic suede T-toe overlays and classic gum sole.",
    price: 100.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1518002171953-a080ee817e1f?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Adidas",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 55,
  },
  {
    name: "Adidas Gazelle Indoor Blue Fusion",
    description: "Originally built for indoor athletics, the Gazelle Indoor shines with ultra-soft suede upper and translucent gum rubber wrap-around outsole.",
    price: 120.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1520256862855-398228c41684?q=80&w=1000&auto=format&fit=crop"]),
    category: "women",
    brand: "Adidas",
    sizes: JSON.stringify(["UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"]),
    stock: 35,
  },
  {
    name: "Adidas Campus 00s Core Black Chunky",
    description: "Puffy tongue, oversized skate laces, and premium chunky suede make the Campus 00s the quintessential Gen-Z streetwear beater.",
    price: 110.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1539185441755-769473a23570?q=80&w=1000&auto=format&fit=crop"]),
    category: "chunky",
    brand: "Adidas",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 45,
  },
  {
    name: "Adidas Superstar Core Black Shell Toe",
    description: "Born on the court, adopted by hip-hop legends. The original shell-toe design with serrated 3-Stripes and smooth full-grain leather.",
    price: 100.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1608231387042-66d1773070a5?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Adidas",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 50,
  },
  {
    name: "Adidas Ultraboost Light Running Shoes",
    description: "Experience epic energy return with Light BOOST foam cushioning — 30% lighter than standard Boost with Continental rubber grip.",
    price: 190.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?q=80&w=1000&auto=format&fit=crop"]),
    category: "sports",
    brand: "Adidas",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 30,
  },
  {
    name: "Adidas Ozweego Chunky Cyber Runner",
    description: "Futuristic 90s aesthetic featuring targeted Adiprene+ cushioning and distinctive translucent nylon support tubing.",
    price: 130.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=1000&auto=format&fit=crop"]),
    category: "chunky",
    brand: "Adidas",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 32,
  },
  {
    name: "Adidas Campus 00s 'Demon Slayer Tanjiro' Edition",
    description: "Checkerboard green & black custom pattern with Nichirin blade heel embroidery and puffy forest green laces.",
    price: 145.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1603808033192-082d6919d3e1?q=80&w=1000&auto=format&fit=crop"]),
    category: "anime",
    brand: "Adidas",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 14,
  },
  {
    name: "Adidas Forum Low 'Dragon Ball Z Shenron'",
    description: "Emerald dragon scale leather textured panels with gold eyelet dubraes and wish-granting fiery orange sole pods.",
    price: 155.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1560769629-975ec94e6a86?q=80&w=1000&auto=format&fit=crop"]),
    category: "anime",
    brand: "Adidas",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"]),
    stock: 10,
  },
  {
    name: "Adidas Forum Low Classic White Royal",
    description: "80s b-ball heritage featuring the signature hook-and-loop ankle strap and premium layered leather cupsole construction.",
    price: 100.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1579338559194-a162d19bf842?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Adidas",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 40,
  },
  {
    name: "Adidas Astir Chunky Y2K Platform",
    description: "Expressive oversized eyelets and wavy chunky tooling inspired by early 2000s maximalist rave and streetwear culture.",
    price: 110.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1605408499391-6368c628ef42?q=80&w=1000&auto=format&fit=crop"]),
    category: "chunky",
    brand: "Adidas",
    sizes: JSON.stringify(["UK 4", "UK 5", "UK 6", "UK 7", "UK 8"]),
    stock: 28,
  },
  {
    name: "Adidas NMD_R1 V3 Primeblue Stealth",
    description: "City exploration kicks built with responsive BOOST midsole and iconic stabilizing midsole plugs in stealth triple black.",
    price: 160.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1565814636199-ae8133055c1c?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Adidas",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 36,
  },
  {
    name: "Adidas Handball Spezial Scarlet Gum",
    description: "First introduced in 1979 for elite handballers, this vintage red suede shoe has become a terrace and street style essential.",
    price: 110.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Adidas",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"]),
    stock: 30,
  },
  {
    name: "Adidas Response CL Trail Tech Olive",
    description: "Rugged retro runner combining durable mesh, synthetic suede overlays, and lightweight EVA cushioning for utilitarian fashion.",
    price: 130.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1595341888016-a392ef81b7de?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Adidas",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 25,
  },
  {
    name: "Adidas Stan Smith Lux Off-White",
    description: "Minimalist luxury perfection featuring buttery-soft leather lining, clean perforated 3-Stripes, and refined gold branding.",
    price: 120.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1533681904393-9ab6eee7e408?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Adidas",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"]),
    stock: 42,
  },
  {
    name: "Adidas Rivalry Low 86 Vintage Chalk",
    description: "Prestige 80s hardwood classic retooled for the modern skate and streetwear rotation with soft two-tone leather.",
    price: 100.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1581655353564-df123a1eb820?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Adidas",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"]),
    stock: 34,
  },
  {
    name: "Adidas Supernova Rise Daily Trainer",
    description: "Powered by Dreamstrike+ superfoam for cloud-like everyday comfort whether hitting morning 5Ks or walking university campuses.",
    price: 140.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1586525198428-225f6f12cff5?q=80&w=1000&auto=format&fit=crop"]),
    category: "sports",
    brand: "Adidas",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 30,
  },
  {
    name: "Adidas adiFOM Q Futuristic Shell",
    description: "Sculpted EVA foam exoskeleton with internal bootie sockliner for avant-garde spaceship aesthetics.",
    price: 120.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=1000&auto=format&fit=crop"]),
    category: "chunky",
    brand: "Adidas",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"]),
    stock: 20,
  },
  {
    name: "Adidas Superstar Kids 360 Slip-On",
    description: "Ultra-flexible honeycomb EVA sole with stretchy textile upper made easy for kids to pull on and off independently.",
    price: 50.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1514989940723-e8e51635b782?q=80&w=1000&auto=format&fit=crop"]),
    category: "kids",
    brand: "Adidas",
    sizes: JSON.stringify(["UK 1", "UK 2", "UK 3", "UK 4", "UK 5"]),
    stock: 50,
  },
  {
    name: "Adidas Adilette 22 Topographic Slide",
    description: "3D-printed topographic map contour lines sculpted from sugarcane bio-foam for revolutionary slide comfort.",
    price: 55.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1608231387042-66d1773070a5?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Adidas",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 45,
  },
  {
    name: "Adidas Forum Low 'Sailor Moon Magical'",
    description: "Pastel pink and celestial lilac patent panels with moon crescent lace charms and glitter translucent outsoles.",
    price: 140.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?q=80&w=1000&auto=format&fit=crop"]),
    category: "anime",
    brand: "Adidas",
    sizes: JSON.stringify(["UK 4", "UK 5", "UK 6", "UK 7", "UK 8"]),
    stock: 16,
  },

  // =========================================================================
  // PUMA (14 Distinct Models)
  // =========================================================================
  {
    name: "Puma RS-X 3D Triple Black Chunky",
    description: "Re-imagined for the digital age with extreme chunky angles, layered mesh and synthetic overlays, and ultra-plush RS cushioning.",
    price: 115.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1608231387042-66d1773070a5?q=80&w=1000&auto=format&fit=crop"]),
    category: "chunky",
    brand: "Puma",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 35,
  },
  {
    name: "Puma Suede Classic XXI Peacoat/White",
    description: "The street icon that debuted in 1968. Full velvety suede upper with gold foil Puma callout and vintage traction cupsole.",
    price: 75.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1518002171953-a080ee817e1f?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Puma",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 60,
  },
  {
    name: "Puma Palermo Leather Gum Sole",
    description: "Direct from the archives, this retro terrace model features classic T-toe construction, signature label tag, and dark gum rubber outsole.",
    price: 90.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Puma",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"]),
    stock: 45,
  },
  {
    name: "Puma Mayze Stack Chunky Platform",
    description: "Sky-high platform height with sawtooth tooling, high-contrast suede Formstrip, and bold elevated girlboss streetwear attitude.",
    price: 110.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=1000&auto=format&fit=crop"]),
    category: "chunky",
    brand: "Puma",
    sizes: JSON.stringify(["UK 4", "UK 5", "UK 6", "UK 7", "UK 8"]),
    stock: 30,
  },
  {
    name: "Puma RS-X 'Cyberpunk Edgerunners' Edition",
    description: "High-octane neon yellow & electric teal hyper-layered sneaker equipped with cybernetic decals and reflective midnight panels.",
    price: 150.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1000&auto=format&fit=crop"]),
    category: "anime",
    brand: "Puma",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 12,
  },
  {
    name: "Puma MB.03 LaMelo Ball Toxic",
    description: "Rare cosmic basketball signature loaded with NITRO foam cushioning, slime splatter print, and alien scratch cutouts.",
    price: 130.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?q=80&w=1000&auto=format&fit=crop"]),
    category: "sports",
    brand: "Puma",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 18,
  },
  {
    name: "Puma Deviate Nitro 2 Carbon Runner",
    description: "Max-performance marathon shoe boasting dual NITRO Elite foam layers and a full-length INNOPLATE carbon composite blade.",
    price: 160.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?q=80&w=1000&auto=format&fit=crop"]),
    category: "sports",
    brand: "Puma",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"]),
    stock: 22,
  },
  {
    name: "Puma Slipstream Bboy High Retro",
    description: "80s breakdancing high-top legend with padded collar, authentic heritage leather panels, and rich hip-hop DNA.",
    price: 110.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Puma",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 25,
  },
  {
    name: "Puma CA Pro Classic White Emerald",
    description: "California West Coast tennis style reimagined with stacked midsole, toe perforations, and clean minimal leather finish.",
    price: 85.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1562183241-b937e95585b6?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Puma",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 50,
  },
  {
    name: "Puma Velophasis Phobia Y2K Mesh",
    description: "Inspired by 2000s tech running with translucent TPU cage, open honeycomb mesh, and dynamic flowing lines.",
    price: 130.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?q=80&w=1000&auto=format&fit=crop"]),
    category: "chunky",
    brand: "Puma",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"]),
    stock: 28,
  },
  {
    name: "Puma 180 Skate Chunky Bread",
    description: "Late 90s oversized skate shoe styling with massive padded mesh tongue and corduroy quarter accents.",
    price: 100.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=1000&auto=format&fit=crop"]),
    category: "chunky",
    brand: "Puma",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"]),
    stock: 35,
  },
  {
    name: "Puma Future Rider Double Play",
    description: "Heritage Fast Rider updated with slim Federbein shock-absorbing outsole and vibrant multi-color nylon blocking.",
    price: 85.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1575537302964-96cd47c06b1b?q=80&w=1000&auto=format&fit=crop"]),
    category: "women",
    brand: "Puma",
    sizes: JSON.stringify(["UK 4", "UK 5", "UK 6", "UK 7", "UK 8"]),
    stock: 40,
  },
  {
    name: "Puma Smash v2 Kids Suede",
    description: "Soft suede kids sneaker with non-marking rubber cupsole and dual velcro straps for hassle-free everyday wear.",
    price: 45.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1514989940723-e8e51635b782?q=80&w=1000&auto=format&fit=crop"]),
    category: "kids",
    brand: "Puma",
    sizes: JSON.stringify(["UK 1", "UK 2", "UK 3", "UK 4", "UK 5"]),
    stock: 55,
  },
  {
    name: "Puma Plexus Sandal Tech Utility",
    description: "Futuristic trail sandal with unique closure lacing system and rugged off-road rubber lugs.",
    price: 110.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1595341888016-a392ef81b7de?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Puma",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 20,
  },

  // =========================================================================
  // NEW BALANCE (14 Distinct Models)
  // =========================================================================
  {
    name: "New Balance 550 White Grey",
    description: "Originally released in 1989 on the hardwood, the 550 has become a global lifestyle icon with premium perforated leather and retro low profile.",
    price: 120.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "New Balance",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11", "UK 12"]),
    stock: 48,
  },
  {
    name: "New Balance 9060 Chunky Sea Salt",
    description: "Reinterpreting familiar 99X elements with warped, exaggerated Y2K design and dramatic sculpted dual-density ABZORB pods.",
    price: 155.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1597045566677-8cf032ed6634?q=80&w=1000&auto=format&fit=crop"]),
    category: "chunky",
    brand: "New Balance",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 25,
  },
  {
    name: "New Balance 530 Silver Metallic Steel",
    description: "Throwback 90s tech dad shoe runner featuring breathable mesh, ABZORB heel cushioning, and sleek silver metallic synthetic overlays.",
    price: 105.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?q=80&w=1000&auto=format&fit=crop"]),
    category: "women",
    brand: "New Balance",
    sizes: JSON.stringify(["UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"]),
    stock: 50,
  },
  {
    name: "New Balance 2002R Protection Pack Rain Cloud",
    description: "Rough-cut raw suede overlays giving an intentional deconstructed aesthetic over N-ergy shock absorbing outsoles.",
    price: 170.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "New Balance",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 18,
  },
  {
    name: "New Balance 1906R Cordura Tech Olive",
    description: "Named after the year New Balance was founded, featuring high-durability Cordura fabric, N-lock lace webbing, and ACTEVA LITE cushioning.",
    price: 160.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "New Balance",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"]),
    stock: 24,
  },
  {
    name: "New Balance 9060 'Dragon Ball Z Shenron'",
    description: "Custom anime concept featuring dragon scale suede panels, golden amber N logo, and mystic moss green chunky pods.",
    price: 180.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1603808033192-082d6919d3e1?q=80&w=1000&auto=format&fit=crop"]),
    category: "anime",
    brand: "New Balance",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 10,
  },
  {
    name: "New Balance 574 Core Navy Heritage",
    description: "The most New Balance shoe ever made. Unpretentious, versatile, and dependable with ENCAP midsole support.",
    price: 90.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1533681904393-9ab6eee7e408?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "New Balance",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 55,
  },
  {
    name: "New Balance 327 Vintage Olive Orange",
    description: "Bold 70s wedge silhouette featuring an asymmetrical oversized 'N' logo and wrap-around trail-inspired lug outsole.",
    price: 100.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=1000&auto=format&fit=crop"]),
    category: "women",
    brand: "New Balance",
    sizes: JSON.stringify(["UK 4", "UK 5", "UK 6", "UK 7", "UK 8"]),
    stock: 35,
  },
  {
    name: "New Balance Fresh Foam X 1080v13",
    description: "Unprecedented plush cushioning for marathon runners and all-day walkers with engineered breathable hypoknit upper.",
    price: 165.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?q=80&w=1000&auto=format&fit=crop"]),
    category: "sports",
    brand: "New Balance",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 30,
  },
  {
    name: "New Balance 990v6 Made in USA Grey",
    description: "Flagship pinnacle running silhouette incorporating FuelCell midsole foam into the legendary premium pigskin suede line.",
    price: 210.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "New Balance",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 15,
  },
  {
    name: "New Balance WRPD Runner Sea Salt",
    description: "Conceptual running aesthetic pushing the boundaries of classic NB proportions with fluid FuelCell contours.",
    price: 150.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1618677831708-0e7fda3148b4?q=80&w=1000&auto=format&fit=crop"]),
    category: "chunky",
    brand: "New Balance",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"]),
    stock: 22,
  },
  {
    name: "New Balance 610v1 Trail Tech Phantom",
    description: "Rugged outdoors 2000s trail shoe with C-CAP cushioning and multi-directional rubber grip teeth.",
    price: 115.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "New Balance",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 30,
  },
  {
    name: "New Balance 574 Kids Hook and Loop",
    description: "Classic suede 574 scaled down for little feet with easy dual velcro straps and lightweight EVA cushioning.",
    price: 55.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1514989940723-e8e51635b782?q=80&w=1000&auto=format&fit=crop"]),
    category: "kids",
    brand: "New Balance",
    sizes: JSON.stringify(["UK 1", "UK 2", "UK 3", "UK 4", "UK 5"]),
    stock: 45,
  },
  {
    name: "New Balance 580 Vintage Indigo Chunky",
    description: "Cult-classic Tokyo street sneaker boasting iconic ROLLBAR stability system and chunky trail-ready profile.",
    price: 130.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1597045566677-8cf032ed6634?q=80&w=1000&auto=format&fit=crop"]),
    category: "chunky",
    brand: "New Balance",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"]),
    stock: 26,
  },

  // =========================================================================
  // VANS (10 Distinct Models)
  // =========================================================================
  {
    name: "Vans Old Skool Classic Black/White",
    description: "The original skate shoe that first bared the iconic leather jazz sidestripe, featuring reinforced toe caps and signature waffle outsoles.",
    price: 75.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Vans",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11", "UK 12"]),
    stock: 65,
  },
  {
    name: "Vans Knu Skool Chunky Y2K Puffy",
    description: "Reissued 90s puffy skate shoe with exaggerated 3D molded sidestripe, heel pull tabs, and ultra-padded tongue.",
    price: 85.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1539185441755-769473a23570?q=80&w=1000&auto=format&fit=crop"]),
    category: "chunky",
    brand: "Vans",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 40,
  },
  {
    name: "Vans Sk8-Hi Tapered Checkerboard",
    description: "Legendary high-top skate shoe with slender ankle profile, sturdy canvas quarter panels, and supportive padded collars.",
    price: 85.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1620138546344-7b2c58516dab?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Vans",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 38,
  },
  {
    name: "Vans Old Skool 'Attack on Titan Survey Corps'",
    description: "Anime tribute featuring Scout Regiment emerald cloak canvas, Wings of Freedom crest on heels, and brown leather straps.",
    price: 110.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=1000&auto=format&fit=crop"]),
    category: "anime",
    brand: "Vans",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 15,
  },
  {
    name: "Vans Classic Slip-On Checkerboard",
    description: "No laces, no fuss. The quintessential low-profile canvas slip-on with elastic side accents and waffle rubber soles.",
    price: 65.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=1000&auto=format&fit=crop"]),
    category: "women",
    brand: "Vans",
    sizes: JSON.stringify(["UK 4", "UK 5", "UK 6", "UK 7", "UK 8"]),
    stock: 55,
  },
  {
    name: "Vans Half Cab 33 DX Anaheim Factory",
    description: "Steve Caballero's iconic mid-top created by skaters cutting down high tops with scissors and duct tape in 1992.",
    price: 95.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1560343090-f0409e92791a?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Vans",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 28,
  },
  {
    name: "Vans UltraRange EXO SE All-Weather",
    description: "Engineered for urban exploration and all-day comfort with full UltraCush Lite midsole and reverse waffle lug grip.",
    price: 115.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?q=80&w=1000&auto=format&fit=crop"]),
    category: "sports",
    brand: "Vans",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"]),
    stock: 30,
  },
  {
    name: "Vans Authentic Core True White",
    description: "The timeless low-top heritage shoe that started it all in Anaheim, California in 1966 with clean white canvas.",
    price: 60.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1533681904393-9ab6eee7e408?q=80&w=1000&auto=format&fit=crop"]),
    category: "women",
    brand: "Vans",
    sizes: JSON.stringify(["UK 4", "UK 5", "UK 6", "UK 7", "UK 8"]),
    stock: 50,
  },
  {
    name: "Vans Old Skool Kids Glow In Dark",
    description: "Fun glowing skeleton footprint graphic on classic durable canvas with double velcro closures for boys and girls.",
    price: 45.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1514989940723-e8e51635b782?q=80&w=1000&auto=format&fit=crop"]),
    category: "kids",
    brand: "Vans",
    sizes: JSON.stringify(["UK 1", "UK 2", "UK 3", "UK 4", "UK 5"]),
    stock: 40,
  },
  {
    name: "Vans Wayvee Skate Multi Suede",
    description: "Modern high-performance skate sneaker featuring translucent reinforced mesh quarters and WAFFLECUP cupsole tech.",
    price: 100.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Vans",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10"]),
    stock: 22,
  },

  // =========================================================================
  // CONVERSE (8 Distinct Models)
  // =========================================================================
  {
    name: "Converse Chuck Taylor All Star 70 High Black",
    description: "Crafted with vintage details, heavier 12oz canvas, higher rubber foxing, and cushioned OrthoLite insoles for supreme comfort.",
    price: 90.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1607522370275-f14206abe5d3?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Converse",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11", "UK 12"]),
    stock: 50,
  },
  {
    name: "Converse Run Star Hike Chunky Platform",
    description: "A chunky platform and jagged two-tone jagged rubber saw sole put an unexpected twist on your everyday Chucks.",
    price: 110.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=1000&auto=format&fit=crop"]),
    category: "chunky",
    brand: "Converse",
    sizes: JSON.stringify(["UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"]),
    stock: 35,
  },
  {
    name: "Converse Chuck 70 'One Piece Straw Hat' Edition",
    description: "Pirate anime tribute featuring Jolly Roger ankle patch, yellow straw stitching, and thousand-sunny treasure map insoles.",
    price: 130.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=1000&auto=format&fit=crop"]),
    category: "anime",
    brand: "Converse",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 14,
  },
  {
    name: "Converse Run Star Motion CX Platform",
    description: "Next-gen exaggerated wavy sculpted CX foam platform with ultra-comfortable ultra-chunky futuristic energy.",
    price: 125.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1605408499391-6368c628ef42?q=80&w=1000&auto=format&fit=crop"]),
    category: "chunky",
    brand: "Converse",
    sizes: JSON.stringify(["UK 5", "UK 6", "UK 7", "UK 8", "UK 9"]),
    stock: 25,
  },
  {
    name: "Converse Chuck 70 Plus Distorted High",
    description: "Asymmetrical collage styling with spliced canvas panels, distorted rubber pinstripes, and exaggerated split lines.",
    price: 105.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1607522370275-f14206abe5d3?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Converse",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"]),
    stock: 30,
  },
  {
    name: "Converse Weapon CX Mid Vintage White",
    description: "80s court battle warrior worn by basketball royalty, upgraded with modern CX foam drop-in midsole cushioning.",
    price: 120.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1579446650033-706d3cb8f219?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Converse",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 22,
  },
  {
    name: "Converse One Star Pro Vintage Suede",
    description: "Tough skate-ready suede with cutout star branding, CONS traction rubber, and impact-absorbing CX sockliner.",
    price: 85.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1560769629-975ec94e6a86?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Converse",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"]),
    stock: 38,
  },
  {
    name: "Converse Chuck Taylor Kids Easy-On",
    description: "Classic high-top aesthetic equipped with dual side hook-and-loop straps so toddlers and kids can gear up fast.",
    price: 45.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1514989940723-e8e51635b782?q=80&w=1000&auto=format&fit=crop"]),
    category: "kids",
    brand: "Converse",
    sizes: JSON.stringify(["UK 1", "UK 2", "UK 3", "UK 4", "UK 5"]),
    stock: 50,
  },

  // =========================================================================
  // ASICS (8 Distinct Models)
  // =========================================================================
  {
    name: "Asics GEL-Kayano 14 Metallic Silver/Black",
    description: "The undisputed king of 2000s technical running aesthetics, featuring original 2008 tooling and exposed GEL technology cushioning.",
    price: 160.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1608231387042-66d1773070a5?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Asics",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 35,
  },
  {
    name: "Asics GEL-NYC Cream Steel Grey",
    description: "Blends the GEL-NIMBUS 3 upper with GEL-CUMULUS 16 tooling for modern city streets and techwear enthusiasts.",
    price: 145.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Asics",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 30,
  },
  {
    name: "Asics GEL-Kayano 14 'Evangelion Unit-01' Limited",
    description: "Mecha anime tribute featuring metallic purple and neon acid green accents inspired by Shinji Ikari's legendary EVA Unit.",
    price: 195.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1580906853203-f493cee9ff28?q=80&w=1000&auto=format&fit=crop"]),
    category: "anime",
    brand: "Asics",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 10,
  },
  {
    name: "Asics GT-2160 Street Runner White/Pure Gold",
    description: "Sleek 2010s running language featuring segmented sole structure and signature industrial technical metallic overlays.",
    price: 130.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Asics",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"]),
    stock: 28,
  },
  {
    name: "Asics Novablast 4 Performance Running",
    description: "Energetic trampoline-inspired FF BLAST PLUS ECO cushioning giving bouncy energy return for daily road running.",
    price: 140.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?q=80&w=1000&auto=format&fit=crop"]),
    category: "sports",
    brand: "Asics",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 35,
  },
  {
    name: "Asics GEL-1130 Retro White/Clay Grey",
    description: "Late 2000s runner celebrated for its open athletic mesh, suede overlays, and exceptional all-day walking support.",
    price: 105.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1562183241-b937e95585b6?q=80&w=1000&auto=format&fit=crop"]),
    category: "women",
    brand: "Asics",
    sizes: JSON.stringify(["UK 4", "UK 5", "UK 6", "UK 7", "UK 8"]),
    stock: 45,
  },
  {
    name: "Asics GEL-Quantum 360 VIII Chunky Street",
    description: "Full 360-degree Scutoid GEL technology wraps the foot in maximum impact resistance with cyberpunk aesthetics.",
    price: 175.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1000&auto=format&fit=crop"]),
    category: "chunky",
    brand: "Asics",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10"]),
    stock: 20,
  },
  {
    name: "Asics GEL-Lyte III OG Split Tongue",
    description: "1990 classic by Shigeyuki Mitsui featuring iconic split tongue construction that eliminates traditional tongue slip.",
    price: 120.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1518002171953-a080ee817e1f?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Asics",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"]),
    stock: 32,
  },

  // =========================================================================
  // FILA (6 Distinct Models)
  // =========================================================================
  {
    name: "Fila Disruptor 2 Premium Chunky White",
    description: "The ultimate iconic dad sneaker with oversized razor-sharp sawtooth platform sole and classic embossed navy/red logo embroidery.",
    price: 80.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?q=80&w=1000&auto=format&fit=crop"]),
    category: "chunky",
    brand: "Fila",
    sizes: JSON.stringify(["UK 4", "UK 5", "UK 6", "UK 7", "UK 8", "UK 9"]),
    stock: 45,
  },
  {
    name: "Fila Ray Tracer Evo Chunky Multi",
    description: "Retro trail-inspired chunky silhouette with dynamic curved overlays, two-tone hiking rope laces, and rugged EVA cushioning.",
    price: 85.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1618677831708-0e7fda3148b4?q=80&w=1000&auto=format&fit=crop"]),
    category: "chunky",
    brand: "Fila",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"]),
    stock: 35,
  },
  {
    name: "Fila Grant Hill 2 Retro 90s High",
    description: "The 1996 hardwood classic famously worn by Grant Hill with bold patent leather triangle mudguard and padded ankle collar.",
    price: 110.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1552346154-21d32810aba3?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Fila",
    sizes: JSON.stringify(["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"]),
    stock: 25,
  },
  {
    name: "Fila FX-100 High Street Leather",
    description: "Old-school 80s high-top street silhouette with branded ankle strap and clean dual-stitched leather panels.",
    price: 90.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1560343090-f0409e92791a?q=80&w=1000&auto=format&fit=crop"]),
    category: "men",
    brand: "Fila",
    sizes: JSON.stringify(["UK 6", "UK 7", "UK 8", "UK 9", "UK 10"]),
    stock: 30,
  },
  {
    name: "Fila Renno Heritage Casual Retro",
    description: "Jogging heritage updated with ripstop nylon, suede overlays, and lightweight Energized foam heel cushioning.",
    price: 75.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1575537302964-96cd47c06b1b?q=80&w=1000&auto=format&fit=crop"]),
    category: "women",
    brand: "Fila",
    sizes: JSON.stringify(["UK 4", "UK 5", "UK 6", "UK 7", "UK 8"]),
    stock: 40,
  },
  {
    name: "Fila Disruptor Kids Chunky Strap",
    description: "Mini sawtooth chunky platform with easy hook-and-loop closure giving kids maximum 90s streetwear swagger.",
    price: 50.0,
    images: JSON.stringify(["https://images.unsplash.com/photo-1514989940723-e8e51635b782?q=80&w=1000&auto=format&fit=crop"]),
    category: "kids",
    brand: "Fila",
    sizes: JSON.stringify(["UK 1", "UK 2", "UK 3", "UK 4", "UK 5"]),
    stock: 50,
  },
];

async function seedDatabase() {
  console.log(`Starting 100% brand-accurate seed process for ${AUTHENTIC_SNEAKERS.length} premium sneakers...`);

  // Step 1: Clean old/duplicate products
  console.log('Resetting and cleaning product records from Neon DB...');
  await prisma.product.deleteMany({});

  console.log(`Seeding ${AUTHENTIC_SNEAKERS.length} strictly mapped authentic shoes into Neon DB...`);

  let count = 0;
  for (const shoe of AUTHENTIC_SNEAKERS) {
    await prisma.product.create({
      data: shoe,
    });
    count++;
    if (count % 25 === 0 || count === AUTHENTIC_SNEAKERS.length) {
      console.log(`✔ Inserted ${count}/${AUTHENTIC_SNEAKERS.length} verified sneakers...`);
    }
  }

  console.log(`\n🎉 Neon Database successfully seeded with ${count} authentic sneakers!`);

  const summary = AUTHENTIC_SNEAKERS.reduce((acc: Record<string, number>, curr) => {
    acc[curr.brand] = (acc[curr.brand] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  console.log('\n📊 Brand Breakdown:');
  Object.entries(summary).forEach(([brand, num]) => {
    console.log(` - ${brand.padEnd(14)}: ${num} items`);
  });
}

seedDatabase()
  .catch((err) => {
    console.error('❌ Seeding error:', err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
